# site settings
title: Parth Patil
subtitle: homepage
email: parthvin@gmail.com
description: I'm not a great programmer,<br/>I'm a just a good programmer with great habits.
url: https://parthvpatil.github.io
baseurl: ''
author:

street_address: Room 3089, Hostel 18, IIT Bombay
city: Powai
state: MH
zip_code: 400076
country: India
phone: +91 9920385585

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/parth.patil.77
github_url: https://github.com/parth1811
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/the_stochastic_guy/
linkedin_url: https://www.linkedin.com/in/parth-patil-256291117/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

pulgins:
  'jekyll-watch'
